"""
Reproduce every number in Tables 1-4 of the report and write results/tables.md.

Run:  python3 reproduce_tables.py            (from projects/fem-wave-1d/)

Nothing here is copied from the report: each table is recomputed from
fem_wave.py, then compared against the values printed in baocao.pdf.
A mismatch beyond the stated tolerance exits non-zero.
"""
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fem_wave import assemble, growth, lam_max, solve, thomas, tri_mul  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "results", "tables.md")

NS = [10, 20, 40, 80, 160, 320]


def order(errs):
    """Empirical order p = log2(E(h) / E(h/2)); None for the first row."""
    out = [None]
    for a, b in zip(errs[:-1], errs[1:]):
        out.append(np.log2(a / b))
    return out


def table1():
    """Spatial convergence, full mass matrix, theta = 0.5."""
    rows = []
    l2s, h1s = [], []
    for N in NS:
        l2, h1 = solve(N, theta=0.5)
        l2s.append(l2)
        h1s.append(h1)
    pl2, ph1 = order(l2s), order(h1s)
    for N, l2, h1, p, q in zip(NS, l2s, h1s, pl2, ph1):
        rows.append((N, 1.0 / N, 0.5 / N, l2, p, h1, q))
    return rows


def table2():
    """Temporal order at fixed N = 200, Richardson differences."""
    N, T, c = 200, 1.0, 1.0
    h = 1.0 / N

    def end_state(theta):
        (Td, Tl), (Sd, Sl), _ = assemble(N)
        dt = theta * h
        M = max(1, int(round(T / dt)))
        dt = T / M
        x = np.linspace(0, 1, N + 1)[1:-1]
        U0 = np.sin(2 * np.pi * x)
        A0 = thomas(Td, Tl, -(c ** 2) * tri_mul(Sd, Sl, U0))
        Um, Uc = U0, U0 + 0.5 * dt ** 2 * A0
        for _ in range(1, M):
            Un = 2 * Uc - Um + dt ** 2 * thomas(Td, Tl, -(c ** 2) * tri_mul(Sd, Sl, Uc))
            Um, Uc = Uc, Un
        return Uc

    thetas = [0.5, 0.25, 0.125, 0.0625, 0.03125]
    states = {t: end_state(t) for t in thetas}
    states[thetas[-1] / 2] = end_state(thetas[-1] / 2)
    diffs = []
    for t in thetas:
        d = states[t] - states[t / 2] if t / 2 in states else end_state(t) - end_state(t / 2)
        diffs.append(np.sqrt(h) * np.linalg.norm(d))
    # normalisation cancels in the ratio, so the order is what matters
    return [(t, t * h, d, p) for t, d, p in zip(thetas, diffs, order(diffs))]


def table3():
    """Stability sweep around theta*, full mass matrix."""
    thetas = [0.5700, 0.5774, 0.5776, 0.5778, 0.5780, 0.5800]
    return [(t, growth(80, t), growth(160, t)) for t in thetas]


def table4():
    """Spatial convergence with the lumped mass matrix at theta = 0.9."""
    l2s, h1s = [], []
    for N in NS:
        l2, h1 = solve(N, theta=0.9, lumped=True)
        l2s.append(l2)
        h1s.append(h1)
    pl2, ph1 = order(l2s), order(h1s)
    return list(zip(NS, [1.0 / N for N in NS], l2s, pl2, h1s, ph1))


def thresholds():
    """Analytic CFL threshold theta* = 2 / (c * h * sqrt(lambda_max))."""
    out = {}
    for N in (80, 160):
        out[N] = 2.0 / ((1.0 / N) * np.sqrt(lam_max(N)))
    out["lumped160"] = 2.0 / ((1.0 / 160) * np.sqrt(lam_max(160, lumped=True)))
    return out


def fmt(v, nd=4):
    return "---" if v is None else f"{v:.{nd}e}"


def main():
    t1, t2, t3, t4 = table1(), table2(), table3(), table4()
    th = thresholds()

    lines = [
        "# Reproduced tables",
        "",
        "Regenerated by `python3 reproduce_tables.py`. Every value below is",
        "computed from `fem_wave.py`, not copied from the report.",
        "",
        "## Table 1 — spatial convergence, full mass, theta = dt/h = 0.5, T = 1",
        "",
        "| N | h | dt | L2 error | order | H1 semi-norm | order |",
        "|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for N, h, dt, l2, p, h1, q in t1:
        lines.append(
            f"| {N} | {h:.6f} | {dt:.6f} | {l2:.4e} | "
            f"{'---' if p is None else f'{p:.2f}'} | {h1:.4e} | "
            f"{'---' if q is None else f'{q:.2f}'} |"
        )

    lines += [
        "",
        "## Table 2 — temporal order, N = 200 fixed, Richardson differences",
        "",
        "| theta | dt | ||U_dt - U_dt/2||_L2 | order |",
        "|---:|---:|---:|---:|",
    ]
    for t, dt, d, p in t2:
        lines.append(f"| {t:.6f} | {dt:.3e} | {d:.6e} | {'---' if p is None else f'{p:.2f}'} |")

    lines += [
        "",
        "## Table 3 — stability sweep, full mass matrix",
        "",
        f"Analytic thresholds: theta*(N=80) = {th[80]:.6f}, "
        f"theta*(N=160) = {th[160]:.6f}, limit 1/sqrt(3) = {1 / np.sqrt(3):.6f}.",
        f"Lumped mass at N=160: theta* = {th['lumped160']:.6f} (limit 1).",
        "",
        "| theta | max|U^M| at N=80 | max|U^M| at N=160 | state |",
        "|---:|---:|---:|:---|",
    ]
    for t, g80, g160 in t3:
        state = []
        state.append("N=80 diverges" if g80 > 1.05 else "N=80 stable")
        state.append("N=160 diverges" if g160 > 1.05 else "N=160 stable")
        lines.append(f"| {t:.4f} | {g80:.3e} | {g160:.3e} | {', '.join(state)} |")

    lines += [
        "",
        "## Table 4 — lumped mass matrix, theta = 0.9",
        "",
        "| N | h | L2 error | order | H1 semi-norm | order |",
        "|---:|---:|---:|---:|---:|---:|",
    ]
    for N, h, l2, p, h1, q in t4:
        lines.append(
            f"| {N} | {h:.6f} | {l2:.4e} | {'---' if p is None else f'{p:.2f}'} | "
            f"{h1:.4e} | {'---' if q is None else f'{q:.2f}'} |"
        )

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nWrote {OUT}")

    # ---- checks against the values printed in the report -------------------
    fails = []

    def close(name, got, want, rtol):
        if not np.isfinite(got) or abs(got - want) > rtol * abs(want):
            fails.append(f"{name}: got {got!r}, report says {want!r}")

    report_l2 = [3.0679e-2, 6.6945e-3, 1.6129e-3, 3.9944e-4, 9.9623e-5, 2.4891e-5]
    report_h1 = [8.0145e-1, 4.0227e-1, 2.0138e-1, 1.0072e-1, 5.0364e-2, 2.5183e-2]
    for row, rl2, rh1 in zip(t1, report_l2, report_h1):
        close(f"Table 1 L2 N={row[0]}", row[3], rl2, 1e-3)
        close(f"Table 1 H1 N={row[0]}", row[5], rh1, 1e-3)

    for t, _, _, p in t2[1:]:
        close(f"Table 2 temporal order theta={t}", p, 2.0, 0.10)

    report_l2_lumped = [2.5370e-2, 6.3636e-3, 1.5922e-3, 3.9815e-4, 9.9542e-5, 2.4886e-5]
    for row, rl2 in zip(t4, report_l2_lumped):
        close(f"Table 4 L2 N={row[0]}", row[2], rl2, 1e-3)

    close("theta*(N=80)", th[80], 0.577684, 1e-5)
    close("theta*(N=160)", th[160], 0.577434, 1e-5)

    # Table 3 as printed in the report. Reproducing these needs the unstable
    # mode seeded at amplitude 1e-8 (report, Sec. 7.3) - see README.
    report_t3 = {
        0.5700: (9.999e-1, 9.999e-1),
        0.5774: (9.997e-1, 1.000e0),
        0.5776: (9.998e-1, 1.002e0),
        0.5778: (9.998e-1, 2.362e0),
        0.5780: (9.999e-1, 2.065e2),
        0.5800: (2.242e2, 1.623e14),
    }
    for t, g80, g160 in t3:
        w80, w160 = report_t3[round(t, 4)]
        close(f"Table 3 N=80 theta={t}", g80, w80, 1e-3)
        close(f"Table 3 N=160 theta={t}", g160, w160, 1e-3)

    # And the qualitative claim the table exists to make: bounded below the
    # analytic threshold, divergent above it.
    for t, g80, g160 in t3:
        for N, g in ((80, g80), (160, g160)):
            if t < th[N] - 5e-4 and not (np.isfinite(g) and g < 1.05):
                fails.append(f"theta={t} below theta*(N={N}) but amplitude {g:.3e}")
            if t > th[N] + 5e-4 and np.isfinite(g) and g < 1.05:
                fails.append(f"theta={t} above theta*(N={N}) but amplitude only {g:.3e}")

    if fails:
        print("\nFAILED checks:")
        for f_ in fails:
            print("  -", f_)
        sys.exit(1)
    print("\nAll checks passed: recomputed values agree with the report.")


if __name__ == "__main__":
    main()
